name: Deploy dev

on:
  workflow_dispatch:
    
env:
  server: 'how-to-deploy-statamic'
  site: 'funkkk.com'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none

      - name: Require Forge CLI
        run: composer global require laravel/forge-cli

      - name: Deploy Site
        run: |
          forge server:switch ${{ env.server }}
          forge deploy ${{ env.site }}
        env:
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
